model_name_or_path: models/VideoMAE-xl
task: video-masking

do_train: true
do_eval: false
do_predict: false
train_dir: /home/ikergarcia/data/gtaai_datasets/dev
validation_dir: /home/ikergarcia/data/gtaai_datasets/dev
test_dirs:
    - /home/ikergarcia/data/gtaai_datasets/test/car_city_day_clear
    - /home/ikergarcia/data/gtaai_datasets/test/car_city_day_rain
    - /home/ikergarcia/data/gtaai_datasets/test/car_city_night_clear
    - /home/ikergarcia/data/gtaai_datasets/test/car_city_night_rain
    - /home/ikergarcia/data/gtaai_datasets/test/car_highway_day_clear
    - /home/ikergarcia/data/gtaai_datasets/test/car_highway_day_rain
    - /home/ikergarcia/data/gtaai_datasets/test/car_highway_night_clear
    - /home/ikergarcia/data/gtaai_datasets/test/car_highway_night_rain

hide_map_probability_train: 0.0
hide_map_probability_validation: 0.0
hide_map_probability_test: 0.0
mask_ratio: 0.9
prediction_loss_only: true

# checkpoint settings
output_dir: models/pretrain/TEDD1104-xl
overwrite_output_dir: true
save_strategy: "no"
evaluation_strategy: "no"

# batch size
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
num_train_epochs: 3

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.00015
weight_decay: 0.05
adam_beta1: 0.9
adam_beta2: 0.95
lr_scheduler_type: cosine
warmup_ratio: 0.03

logging_strategy: steps
logging_first_step: true
logging_steps: 100
report_to: wandb
run_name: "TEDD1104-xl"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
bf16_full_eval: true
dataloader_num_workers: 16
