model_name_or_path: models/pretrain/TEDD1104-small
task: video-classification
deepspeed: configs/deepspeed/deepspeed_zero3.json

do_train: true
do_eval: true
do_predict: true
train_dir: /ikerlariak/igarcia945/gtaai_datasets/train
validation_dir: /ikerlariak/igarcia945/gtaai_datasets/dev
test_dirs:
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_city_day_clear
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_city_day_rain
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_city_night_clear
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_city_night_rain
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_highway_day_clear
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_highway_day_rain
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_highway_night_clear
    - /ikerlariak/igarcia945/gtaai_datasets/test/car_highway_night_rain

hide_map_probability_train: 0.0
hide_map_probability_validation: 0.0
hide_map_probability_test: 0.0
mask_ratio: 0.9

# checkpoint settings
output_dir: models/video-classification/TEDD1104-small
overwrite_output_dir: true
load_best_model_at_end: true
save_strategy: "steps"
save_steps: 1000
save_total_limit: 1
evaluation_strategy: "steps"
eval_steps: 1000
metric_for_best_model: "acc_k1_macro"
greater_is_better: true

# batch size
per_device_train_batch_size: 32
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
num_train_epochs: 3

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.001
weight_decay: 0.05
adam_beta1: 0.9
adam_beta2: 0.95
lr_scheduler_type: cosine
warmup_ratio: 0.03

logging_strategy: steps
logging_first_step: true
logging_steps: 100
report_to: wandb
run_name: "TEDD1104-small"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
bf16_full_eval: true
1000dataloader_num_workers: 64
