model_name_or_path: models/VideoMAE-large_ps30
task: video-classification
deepspeed: configs/deepspeed/deepspeed_zero3.json

do_train: true
do_eval: true
do_predict: true
train_dir: ../gtaai_dataset/train
validation_dir: ../gtaai_dataset/dev
test_dirs:
    - ../gtaai_dataset/test/car_city_day_clear
    - ../gtaai_dataset/test/car_city_day_rain
    - ../gtaai_dataset/test/car_city_night_clear
    - ../gtaai_dataset/test/car_city_night_rain
    - ../gtaai_dataset/test/car_highway_day_clear
    - ../gtaai_dataset/test/car_highway_day_rain
    - ../gtaai_dataset/test/car_highway_night_clear
    - ../gtaai_dataset/test/car_highway_night_rain

hide_map_probability_train: 0.0
hide_map_probability_validation: 0.0
hide_map_probability_test: 0.0
mask_ratio: 0.2

# checkpoint settings
output_dir: models/video-classification/TEDD1104-large_ps30
overwrite_output_dir: true
load_best_model_at_end: true
save_strategy: "steps"
save_steps: 1000
save_total_limit: 2
evaluation_strategy: "steps"
eval_steps: 1000
metric_for_best_model: "acc_k1_macro"
greater_is_better: true

# batch size
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 4
num_train_epochs: 20

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.00002
weight_decay: 0.001
adam_beta1: 0.9
adam_beta2: 0.95
lr_scheduler_type: cosine
warmup_ratio: 0.1

logging_strategy: steps
logging_first_step: true
logging_steps: 100
report_to: wandb
run_name: "TEDD1104-large_ps30"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
bf16_full_eval: true
dataloader_num_workers: 8
